########################### NETWORKS
networks:
  default:
    driver: bridge
  lsio:
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/16"
        - gateway: "172.21.0.1"
    name: lsio

services:
  ############################# WEBSERVER
  # Swag - webserver, reverse proxy
  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.3
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    cap_add:
      - NET_ADMIN
    ports:
      - 449:443
      # - 89:80
      # - 81:81
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${DOMAINNAME}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - CERTPROVIDER=zerossl
      - STAGING=false
      - EMAIL=${CLOUDFLARE_EMAIL}
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-maxmind
      - MAXMINDDB_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}
      - HAS_IPV6=false
      - UMASK=022
    volumes:
      - ${USERDIR}/swag:/config

  # Cloudflare DDNS - Dynamic DNS Updater
  cf-ddns:
    container_name: cloudflare-ddns
    image: oznu/cloudflare-ddns
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.5
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - API_KEY=${API_KEY}
      - ZONE=${DOMAINNAME}
      - PROXIED=false
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - DNS_SERVER=1.1.1.1
      - CRON="@daily"

  ############################# FRONTENDS
  # Organizr - Unified Frontend
  organizr:
    container_name: organizr
    image: ghcr.io/organizr/organizr
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 88:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - fpm=true #true or false | using true will provide better performance
    volumes:
      - ${USERDIR}/organizr:/config

  ############################# INDEXERS
  # Prowlarr - Hydra and Jackett combined
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.7
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HAS_IPV6=false
      - UMASK=022
    volumes:
      - ${USERDIR}/prowlarr:/config

  ############################# DOWNLOADERS
  # SABnzbd - nzb downloader
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.8
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 9998:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HAS_IPV6=false
      - UMASK=022
      - DOCKER_MODS=linuxserver/mods:sabnzbd-par2cmdline-turbo
    volumes:
      - ${USERDIR}/sabnzbd:/config
      - ${DATADIR}/usenet:/data/usenet:rw

  # qBittorrent - torrent downloader
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.9
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 9091:9091
      - 65118:65118
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=9091
      - HAS_IPV6=false
      - UMASK=022
    volumes:
      - ${USERDIR}/qBittorrent:/config
      - ${DATADIR}/torrents:/data/torrents

  ############################# MEDIA SEARCH/INDEX
  # Radarr - Movies
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.10
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HAS_IPV6=false
      - UMASK=022
    volumes:
      - ${USERDIR}/radarr:/config
      - ${DATADIR}:/data

  # Sonarr - TV
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.11
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HAS_IPV6=false
      - UMASK=022
    volumes:
      - ${USERDIR}/sonarr:/config
      - ${DATADIR}:/data

  # Lidarr – Music
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.12
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HAS_IPV6=false
      - UMASK=022
      - DOCKER_MODS=linuxserver/mods:lidarr-flac2mp3
    volumes:
      - ${USERDIR}/lidarr:/config
      - ${DATADIR}:/data

  # Bazarr – Subtitle Management
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.13
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HAS_IPV6=false
      - UMASK=022
    volumes:
      - ${USERDIR}/bazarr:/config
      - ${DATADIR}/media:/data/media

  # Recyclarr – Update Radarr/Sonarr quality Profiles
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.14
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    user: 1056:65547
    volumes:
      - ${USERDIR}/recyclarr:/config
    environment:
      - TZ=${TZ}

  # Tdarr - Video conversion
  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.15
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 8265:8265
      - 8266:8266
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=TdarrNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - THREADS_WORKER_INIT_TIMEOUT=200000
      - gpus=all
    volumes:
      - ${USERDIR}:/app/server
      - ${USERDIR}/Tdarr/Configs:/app/configs
      - ${USERDIR}/Tdarr/Logs:/app/logs
      - ${DATADIR}/media/Transcode:/temp
      - ${DATADIR}/media:/data/media

  ############################# HOME THEATRE
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    # networks:
      # lsio:
        # ipv4_address: 172.21.2.16
    network_mode: "host" #if you use this, comment networks and port entry
    # ports:
      # - 32400:32400
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=docker
      - HAS_IPV6=false
      - UMASK=022
    volumes:
      - ${USERDIR}/plex:/config
      - ${DATADIR}/media:/data/media
    devices:
      - /dev/dri:/dev/dri # optional: if Syno has Intel CPU & you want HW transcoding
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
      
  ############################# PLEX MONITORING
  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.17
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HAS_IPV6=false
      - UMASK=022
    volumes:
      - ${USERDIR}/tautulli:/config
      - ${USERDIR}/plex:/plex

  ############################# BOOK LIBRARY MANAGEMENT
  # Calibre – Content server
  calibre:
    container_name: calibre
    image: lscr.io/linuxserver/calibre:latest
    security_opt:
      - seccomp:unconfined #optional
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.18
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 7080:8080
      - 8081:8081
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISABLE_AUTH=true
      - HAS_IPV6=false
      - UMASK=022
    volumes:
      - ${USERDIR}/calibre:/config
      - ${DATADIR}:/data

  # Readarr - Books
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.19
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 8787:8787
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HAS_IPV6=false
      - UMASK=022
    volumes:
      - ${USERDIR}/readarr:/config
      - ${USERDIR}/calibre:/calibre
      - ${DATADIR}:/data

  ############################# SYSTEM MANAGEMENT/MONITORING
  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.20
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 9999:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOZZLE_LEVEL=error
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ############################# SECURITY/PASSWORD MANAGEMENT
  # Vaultwarden - Locally-hosted Bitwarden
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.2.21
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 8269:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - ADMIN_TOKEN=${VAULTWARDEN_TOKEN}
    volumes:
      - ${VAULTDIR}:/data
