version: "2.1"
########################### NETWORKS
networks:
  lsio:
    name: lsio
    driver: bridge
  default:
    driver: bridge

########################### SERVICES
  # Swag - webserver, reverse proxy
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    logging:
      driver: local
    networks:
      - lsio
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${DOMAINNAME}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - CERTPROVIDER=zerossl
      - STAGING=false
      - EMAIL=${CLOUDFLARE_EMAIL}
      - MAXMINDDB_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}
    volumes:
      - ${USERDIR}/swag:/config
    ports:
      - 449:443
      - 89:80
    restart: unless-stopped

  ############################# MEDIA PLAYERS
  # Plex
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    logging:
      driver: local
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_TOKEN}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - gpus=all
    volumes:    
      - ${USERDIR}/plex:/config
      - ${DATADIR}:/data
    restart: unless-stopped

  ############################# FRONTENDS
  # Organizr - Unified Frontend
  organizr:
    image: organizr/organizr
    container_name: organizr
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - fpm=true #true or false | using true will provide better performance
    volumes:
      - ${USERDIR}/organizr:/config
    ports:
      - 88:80
    restart: unless-stopped

  ############################# PVRS
  # Sonarr - TV
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/sonarr:/config
      - ${DATADIR}:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  # Radarr - Movies
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/radarr:/config
      - ${DATADIR}:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  # Bazarr - subtitle searching and downloading, based on release filename
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/bazarr:/config
      - ${DATADIR}:/data
    ports:
      - 6767:6767
    restart: unless-stopped

  ############################# BOOKS
  # Calibre – Content server
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISABLE_AUTH=true
      # - CALIBRE_CONFIG_DIRECTORY=${USERDIR}/calibre
      # - CALIBRE_TEMP_DIR=${USERDIR}/calibre/temp
      # - CALIBRE_CACHE_DIRECTORY=${USERDIR}/calibre/temp
      # - PASSWORD= #optional
      # - CLI_ARGS= #optional
    volumes:
      - ${USERDIR}/calibre:/config
      - ${DATADIR}:/data
    ports:
      - 9998:8080
      - 8081:8081
    restart: unless-stopped
    
  # Calibre-web  – Ebooks and Management
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #necessary for Google oAuth
      - OAUTHLIB_INSECURE_TRANSPORT=1 #necessary for Google oAuth
    volumes:
      - ${USERDIR}/calibre_web:/config
      - ${DATADIR}:/data
    ports:
      - 8083:8083
    restart: unless-stopped

  # Readarr  – Library Management
  readarr:
    image: ghcr.io/linuxserver/readarr:nightly
    container_name: readarr
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/readarr:/config
      - ${DATADIR}:/data
      - ${MEDIADIR}/library:/books
    ports:
      - 8787:8787
    restart: unless-stopped

  ############################# MUSIC
  # Lidarr  – Music Management
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/lidarr:/config
      - ${DATADIR}:/data
    ports:
      - 8686:8686
    restart: unless-stopped

  ############################# INDEXERS
  # Prowlarr - Hydra and Jackett combined
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/prowlarr:/config
      - ${DATADIR}:/data
    ports:
      - 9696:9696
    restart: unless-stopped

  ############################# DOWNLOADERS
  # SABnzbd - Binary newsgrabber (NZB downloader)
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/sabnzbd:/config
      - ${DATADIR}:/data
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped  

  # Deluge - Torrents
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${USERDIR}/deluge:/config
      - ${DATADIR}:/data
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  ############################# SYSTEM MANAGEMENT/MONITORING
  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    logging:
      driver: local
    networks:
      - lsio
    ports:
      - 9999:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOZZLE_LEVEL=error
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
      # - DOCKER_HOST=tcp://socket-proxy:2375
      # - DOZZLE_FILTER="label=log_me" # limits logs to containers with this label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # Cloudflare DDNS - Dynamic DNS Updater
  cf-ddns:
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns
    logging:
      driver: local
    network_mode: host
    environment:
      - API_KEY=${CLOUDFLARE_API_KEY}
      - ZONE=${DOMAINNAME}
      - PROXIED=false
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - DNS_SERVER=1.1.1.1
      - CRON="@daily"
    restart: unless-stopped
    
  # Watchtower - Automatic Update of Containers/Apps
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - TZ=${TZ}
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=warn
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=43200
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  ############################# MEDIA FILE MANAGEMENT
  # Video conversion - tdarr
  tdarr:
    image: haveagitgat/tdarr
    container_name: tdarr
    logging:
      driver: local
    networks:
      - lsio
    ports:
      - 8265:8265
      - 8266:8266
      - 8267:8267
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ${USERDIR}:/app/server
      - ${USERDIR}/Tdarr/Configs:/app/configs
      - ${USERDIR}/Tdarr/Logs:/app/logs
      - ${DATADIR}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - serverIP=0.0.0.0
      - webUIPort=8265
      - serverPort=8266
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - gpus=all
    restart: always

  tdarr_node:
    image: haveagitgat/tdarr_node
    container_name: tdarr_node
    logging:
      driver: local
    network_mode: service:tdarr
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ${USERDIR}:/app/server
      - ${USERDIR}/Tdarr/Configs:/app/configs
      - ${USERDIR}/Tdarr/Logs:/app/logs
      - ${DATADIR}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - gpus=all
      - nodeID=MainNode
      - nodeIP=0.0.0.0
      - nodePort=8267
      - serverIP=0.0.0.0
      - serverPort=8266
    restart: always

  ############################# SECURITY/PASSWORD MANAGEMENT
  # Vaultarden - Locally-hosted Bitwarden
  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    logging:
      driver: local
    networks:
      - lsio
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - ADMIN_TOKEN=${VAULTWARDEN_TOKEN}
    volumes:
      - ${VAULTDIR}:/data
    restart: unless-stopped
