version: "3.2"
########################### NETWORKS
networks:
  default:
    driver: bridge
  lsio:
    driver: bridge
    external:
      name: lsio
services:
  ############################# WEBSERVER
  # Swag - webserver, reverse proxy
  swag:
    container_name: swag
    image: ghcr.io/linuxserver/swag
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 449:443
      # - 89:80
      - 81:81
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${DOMAINNAME}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - CERTPROVIDER=zerossl
      - STAGING=false
      - EMAIL=${CLOUDFLARE_EMAIL}
      - DOCKER_MODS=linuxserver/mods:swag-maxmind|linuxserver/mods:swag-dashboard|linuxserver/mods:swag-cloudflare-real-ip
      - MAXMINDDB_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/swag:/config

  # Cloudflare DDNS - Dynamic DNS Updater
  cf-ddns:
    container_name: cloudflare-ddns
    image: oznu/cloudflare-ddns
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - API_KEY=${API_KEY}
      - ZONE=${DOMAINNAME}
      - PROXIED=false
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - DNS_SERVER=1.1.1.1
      - CRON="@daily"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  ############################# FRONTENDS
  # Organizr - Unified Frontend
  organizr:
    container_name: organizr
    image: ghcr.io/organizr/organizr
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 88:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - fpm=true #true or false | using true will provide better performance
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/organizr:/config

  ############################# INDEXERS
  # Prowlarr - Hydra and Jackett combined
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:develop
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - ARGS=
    volumes:
      - ${USERDIR}/prowlarr:/config:rw

  ############################# DOWNLOADERS
  # SABnzbd - nzb downloader
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/linuxserver/sabnzbd
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8087:8080
      - 9090:9090
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/sabnzbd:/config
      - ${DATADIR}/usenet:/data/usenet:rw

  # Deluge - torrent downloader
  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
      - DELUGE_LOGLEVEL=error #optional
      - PYTHON_EGG_CACHE=/config/plugins/.python-eggs
      - LAN_NETWORK=110.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/deluge:/config:rw
      - ${DATADIR}/torrents:/data/torrents:rw
      
  ############################# MEDIA SEARCH/INDEX
  # Radarr - Movies
  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/radarr:/config
      - ${DATADIR}:/data

  # Sonarr - TV
  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/sonarr:/config
      - ${DATADIR}:/data

  # Lidarr – Music
  lidarr:
    container_name: lidarr
    image: ghcr.io/linuxserver/lidarr
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - DOCKER_MODS=linuxserver/mods:lidarr-flac2mp3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/lidarr:/config
      - ${DATADIR}:/data

  # Readarr - Books
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8787:8787
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/readarr:/config
      - ${DATADIR}:/data
      
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    restart: unless-stopped
    init: true
    networks:
      - lsio
    volumes:
      - ${USERDIR}/recyclarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  ############################# MEDIA AUGMENTATION
  # Bazarr  – Subtitle Management
  bazarr:
    container_name: bazarr
    image: ghcr.io/linuxserver/bazarr
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/bazarr:/config
      - ${DATADIR}/media:/data/media

    # Tdarr - Video conversion
  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8265:8265
      - 8266:8266
      - 8267:8267
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=TdarrNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - THREADS_WORKER_INIT_TIMEOUT=200000
      - gpus=all
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}:/app/server
      - ${USERDIR}/Tdarr/Configs:/app/configs
      - ${USERDIR}/Tdarr/Logs:/app/logs
      - ${DATADIR}/media/transcode:/temp
      - ${DATADIR}/media:/data/media

  ############################# HOME THEATRE
  plex:
    container_name: plex
    image: ghcr.io/linuxserver/plex
    restart: unless-stopped
    network_mode: "host" #and if you use this, comment out the port entry
    # networks:
      # - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    # ports:
      # - 32400:32400
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - ARGS=
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
      - ALLOWED_NETWORKS=192.168.1.0/24
      - PLEX_PASS=${PLEX_PASS}
      - VERSION=docker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/plex:/config:rw
      - ${DATADIR}/media:/data/media:rw
    devices:
      - /dev/dri:/dev/dri # optional: if Syno has an Intel CPU with quicksync and you want hardware transcoding
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128

  ############################# BOOK LIBRARY MANAGEMENT
  # Calibre – Content server
  calibre:
    container_name: calibre
    image: ghcr.io/linuxserver/calibre
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8082:8080
      - 8081:8081
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISABLE_AUTH=true
      - CALIBRE_CONFIG_DIRECTORY=/config
      - CALIBRE_CACHE_DIRECTORY=/cache
      - CALIBRE_TEMP_DIR=/temp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/calibre:/config
      - ${USERDIR}/calibre/cache:/cache
      - ${USERDIR}/calibre/temp:/temp
      - ${DATADIR}:/data
    
  # Calibre-web  – Ebooks and Management
  calibre-web:
    container_name: calibre-web
    image: ghcr.io/linuxserver/calibre-web
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8083:8083
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #necessary for Google oAuth
      - OAUTHLIB_INSECURE_TRANSPORT=1 #necessary for Google oAuth
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/calibre_web:/config
      - ${DATADIR}:/data

  ############################# SYSTEM MANAGEMENT/MONITORING
  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 9999:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOZZLE_LEVEL=error
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
      # - DOCKER_HOST=tcp://socket-proxy:2375
      # - DOZZLE_FILTER="label=log_me" # limits logs to containers with this label
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}:/data
   
  # Watchtower - Automatic Update of Containers/Apps
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=warn
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=43200
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

  ############################# SECURITY/PASSWORD MANAGEMENT
  # Vaultarden - Locally-hosted Bitwarden
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server
    restart: unless-stopped
    networks:
      - lsio
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8269:80
    environment:
      - PUID=${SUDOID}
      - PGID=${SUDOGRP}
      - TZ=${TZ}
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - ADMIN_TOKEN=${VAULTWARDEN_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VAULTDIR}:/data
