########################### NETWORKS
networks:
  default:
    driver: bridge
  lsio:
    driver: bridge
    name: lsio
    ipam:
      driver: default
      config:
      -
        subnet: 172.21.199.0/24
        gateway: 192.168.1.1

services:
  ############################# WEBSERVER
  # Swag - webserver, reverse proxy
  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.100
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 449:443
      - 89:80
      - 81:81
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${DOMAINNAME}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - CERTPROVIDER=zerossl
      - STAGING=false
      - EMAIL=${CLOUDFLARE_EMAIL}
      - DOCKER_MODS=linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-maxmind|linuxserver/mods:swag-dashboard
      - MAXMINDDB_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}
    volumes:
      - ${USERDIR}/swag:/config
    
  # Cloudflare DDNS - Dynamic DNS Updater
  cf-ddns:
    container_name: cloudflare-ddns
    image: oznu/cloudflare-ddns
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.101
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - API_KEY=${API_KEY}
      - ZONE=${DOMAINNAME}
      - PROXIED=false
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - DNS_SERVER=1.1.1.1
      - CRON="@daily"

  ############################# FRONTENDS
  # Organizr - Unified Frontend
  organizr:
    container_name: organizr
    image: ghcr.io/organizr/organizr
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.102
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 88:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - fpm=true #true or false | using true will provide better performance
    volumes:
      - ${USERDIR}/organizr:/config

  ############################# INDEXERS
  # Prowlarr - Hydra and Jackett combined
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.103
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/prowlarr:/config

  ############################# DOWNLOADERS
  # SABnzbd - nzb downloader
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.104
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8080:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/sabnzbd:/config
      - ${DATADIR}/usenet:/data/usenet

  # qBittorrent - torrent downloader
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.105
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports: #re-enable all if dropping VPN
      - 9091:9091
      - 6882:6882
      - 6882:6882/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=9091
    volumes:
      - ${USERDIR}:/config
      - ${DATADIR}/torrents:/data/torrents

  ############################# MEDIA SEARCH/INDEX
  # Radarr - Movies
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.106
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/radarr:/config
      - ${DATADIR}:/data

  # Sonarr - TV
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.107
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/sonarr:/config
      - ${DATADIR}:/data

  # Lidarr – Music
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.108
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/lidarr:/config
      - ${DATADIR}:/data

  # Readarr - Books
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.109
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8787:8787
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/readarr:/config
      - ${DATADIR}:/data

  ############################# MEDIA AUGMENTATION
  # Recyclarr  – Auto-update download profiles for Sonarr and Radarr      
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    restart: unless-stopped
    init: true
    user: ${PUID}:${PGID}
    networks:
      lsio:
        ipv4_address: 172.21.199.110
    volumes:
      - ${USERDIR}/recyclarr:/config
    environment:
      - TZ=${TZ}

  # Bazarr  – Subtitle Management
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.111
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/bazarr:/config
      - ${DATADIR}/media:/data/media

  # Tdarr - Video conversion
  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.112
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8265:8265
      - 8266:8266
      - 8267:8267
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=TdarrNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - THREADS_WORKER_INIT_TIMEOUT=200000
      - gpus=all
    volumes:
      - ${USERDIR}:/app/server
      - ${USERDIR}/Tdarr/Configs:/app/configs
      - ${USERDIR}/Tdarr/Logs:/app/logs
      - ${DATADIR}/media/Transcode:/temp
      - ${DATADIR}/media:/data/media

  ############################# HOME THEATRE
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: "host" #and if you use this, comment out the port entry
    # networks:
      # lsio:
        # ipv4_address: 172.21.199.113
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    # ports:
      # - 32400:32400
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://your_lan_plex_ip:32400
      - VERSION=docker
    volumes:
      - ${USERDIR}/plex:/config
      - ${DATADIR}/media:/data/media
    devices:
      - /dev/dri:/dev/dri # optional: if Syno has Intel CPU & you want HW transcoding
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
      
  ############################# PLEX MONITORING
  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.114
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/tautulli:/config
      - ${USERDIR}/plex:/plex

  ############################# BOOK LIBRARY MANAGEMENT
  # Calibre – Content server
  calibre:
    container_name: calibre
    image: lscr.io/linuxserver/calibre:latest
    security_opt:
      - seccomp:unconfined #optional
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.115
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8082:8080
      - 8081:8081
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISABLE_AUTH=true
    volumes:
      - ${USERDIR}/calibre:/config
      - ${DATADIR}:/data
    
  # Calibre-web  – Ebooks and Management
  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:latest
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.116
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8083:8083
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #necessary for Google oAuth
      # - OAUTHLIB_INSECURE_TRANSPORT=1 #necessary for Google oAuth
    volumes:
      - ${USERDIR}/calibre_web:/config
      - ${DATADIR}:/data

  ############################# SYSTEM MANAGEMENT/MONITORING
  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.117
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 9999:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOZZLE_LEVEL=error
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER="status=running"
      # - DOZZLE_FILTER="label=log_me" # limits logs to containers with this label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}:/data
   
  # Watchtower - Automatic Update of Containers/Apps
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    network_mode: "host" #and if you use this, comment out the port entry
    # networks:
      # lsio:
        # ipv4_address: 172.21.199.118
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    # ports:
      # - 8088:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=warn
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=43200
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ############################# SECURITY/PASSWORD MANAGEMENT
  # Vaultarden - Locally-hosted Bitwarden
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server
    restart: unless-stopped
    networks:
      lsio:
        ipv4_address: 172.21.199.119
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 8269:80
    environment:
      - PUID=${SUDOID}
      - PGID=${SUDOGRP}
      - TZ=${TZ}
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - ADMIN_TOKEN=${VAULTWARDEN_TOKEN}
    volumes:
      - ${VAULTDIR}:/data
